### ISSUE TITLE
Project release checklist

### ISSUE THREAD

**Issue by fejes713** [fejes713/accessibility-guide#3]
### Project:
- [x] Generate website using `hyperapp` @fejes713 
- [x] Set up Netlify
- [x] Make sure website is accessible
- [x] Have at least 30ish snippets until launch (we're at 20 now)
- [x] Buy domain: https://webaccessibility.guide
- [x] Generate README.md (thanks @Chalarangelo)
- [x] Think of header introductory text
- [x] Graphics and fancy clean CSS (ask @atomiks & @petrovicstefanrs for inspiration & help)
- [x] ESLint & Prettier setup, possibly with git-hooks
- [x] Write contributor guidelines @fejes713 
- [x] Logo design

### Launch:
- [x] Reddit & Twitter community
- [x] Product Hunt
- [x] LinkedIn promotion
- [x] Motivation, people from the industry etc.
- [x] Set up analytics

**Comment by fejes713** [comment]
Well, it's live. Time to close I guess. 🎉
